const CATEGORIES = {
    legumes: [
        "pics/les légumes/la betterave.png",
        "pics/les légumes/la carotte.png",
        "pics/les légumes/la courgette.png",
        "pics/les légumes/la laitue.png",
        "pics/les légumes/la patate douce.png",
        "pics/les légumes/la pomme de terre.png",
        "pics/les légumes/la tomate.png",
        "pics/les légumes/le brocoli.png",
        "pics/les légumes/le chou de Bruxelles.png",
        "pics/les légumes/le chou-fleur.png",
        "pics/les légumes/le chou.png",
        "pics/les légumes/le concombre.png",
        "pics/les légumes/le céleri.png",
        "pics/les légumes/le haricot vert.png",
        "pics/les légumes/le petit pois.png",
        "pics/les légumes/le poireau.png",
        "pics/les légumes/le poivron.png",
        "pics/les légumes/le potiron.png",
        "pics/les légumes/le radis.png",
        "pics/les légumes/les épinards.png",
        "pics/les légumes/l'ail.png",
        "pics/les légumes/l'artichaut.png",
        "pics/les légumes/l'aubergine.png",
        "pics/les légumes/l'oignon.png"
    ],

    fruits: [
        "pics/les fruits/la banane.png",
        "pics/les fruits/la cerise.png",
        "pics/les fruits/la fraise.png",
        "pics/les fruits/la framboise.png",
        "pics/les fruits/la grenade.png",
        "pics/les fruits/la mangue.png",
        "pics/les fruits/la myrtille.png",
        "pics/les fruits/la mûre.png",
        "pics/les fruits/la papaye.png",
        "pics/les fruits/la pastèque.png",
        "pics/les fruits/la poire.png",
        "pics/les fruits/la pomme.png",
        "pics/les fruits/la prune.png",
        "pics/les fruits/la pêche.png",
        "pics/les fruits/le cassis.png",
        "pics/les fruits/le citron vert.png",
        "pics/les fruits/le citron.png",
        "pics/les fruits/le kaki.png",
        "pics/les fruits/le kiwi.png",
        "pics/les fruits/le melon.png",
        "pics/les fruits/le raisin.png",
        "pics/les fruits/l'abricot.png",
        "pics/les fruits/l'ananas.png",
        "pics/les fruits/l'orange.png"
    ],

    spices: [
        "pics/les épices/la cannelle.png",
        "pics/les épices/la cardamome.png",
        "pics/les épices/la coriandre.png",
        "pics/les épices/le laurier.png",
        "pics/les épices/la moutarde.png",
        "pics/les épices/la muscade.png",
        "pics/les épices/le sésame noire.png",
        "pics/les épices/la vanille.png",
        "pics/les épices/le basilic.png",
        "pics/les épices/le clou de girofle.png",
        "pics/les épices/le cumin.png",
        "pics/les épices/le curcuma.png",
        "pics/les épices/le curry.png",
        "pics/les épices/le fenouil.png",
        "pics/les épices/le gingembre.png",
        "pics/les épices/le paprika.png",
        "pics/les épices/le poivre.png",
        "pics/les épices/le piment.png",
        "pics/les épices/le romarin.png",
        "pics/les épices/le safran.png",
        "pics/les épices/le thym.png",
        "pics/les épices/l'ail.png",
        "pics/les épices/l'anis étoilé.png",
        "pics/les épices/l'origan.png"
    ],

    herbs: [
        "pics/les herbes aromatiques/la ciboulette.png",
        "pics/les herbes aromatiques/la citronnelle.png",
        "pics/les herbes aromatiques/la coriandre.png",
        "pics/les herbes aromatiques/la lavande.png",
        "pics/les herbes aromatiques/la livèche.png",
        "pics/les herbes aromatiques/la marjolaine.png",
        "pics/les herbes aromatiques/la menthe.png",
        "pics/les herbes aromatiques/la mélisse.png",
        "pics/les herbes aromatiques/la roquette.png",
        "pics/les herbes aromatiques/la sarriette.png",
        "pics/les herbes aromatiques/la sauge.png",
        "pics/les herbes aromatiques/le basilic.png",
        "pics/les herbes aromatiques/le cerfeuil.png",
        "pics/les herbes aromatiques/le céleri perpétuel.png",
        "pics/les herbes aromatiques/le laurier-sauce.png",
        "pics/les herbes aromatiques/le laurier.png",
        "pics/les herbes aromatiques/le persil.png",
        "pics/les herbes aromatiques/le romarin.png",
        "pics/les herbes aromatiques/le shiso.png",
        "pics/les herbes aromatiques/le thym citron.png",
        "pics/les herbes aromatiques/le thym.png",
        "pics/les herbes aromatiques/l'aneth.png",
        "pics/les herbes aromatiques/l'estragon.png",
        "pics/les herbes aromatiques/l'origan.png"
    ],

    inner_organs: [
        "pics/les organes internes/l'estomac.png",
        "pics/les organes internes/l'œsophage.png",
        "pics/les organes internes/la rate.png",
        "pics/les organes internes/la vessie.png",
        "pics/les organes internes/la vésicule biliaire.png",
        "pics/les organes internes/le cerveau.png",
        "pics/les organes internes/le cœur.png",
        "pics/les organes internes/le foie.png",
        "pics/les organes internes/le pancréas.png",
        "pics/les organes internes/les intestins.png",
        "pics/les organes internes/les poumons.png",
        "pics/les organes internes/les reins.png"
    ],

    dishes: [
        "pics/les couverts les verres et la vaisselle/l'assiette creuse.png",
        "pics/les couverts les verres et la vaisselle/l'assiette plate.png",
        "pics/les couverts les verres et la vaisselle/l'assiette à dessert.png",
        "pics/les couverts les verres et la vaisselle/la cuillère à café.png",
        "pics/les couverts les verres et la vaisselle/la cuillère.png",
        "pics/les couverts les verres et la vaisselle/la fourchette à dessert.png",
        "pics/les couverts les verres et la vaisselle/la fourchette.png",
        "pics/les couverts les verres et la vaisselle/la louche.png",
        "pics/les couverts les verres et la vaisselle/la petite assiette.png",
        "pics/les couverts les verres et la vaisselle/la pince à servir.png",
        "pics/les couverts les verres et la vaisselle/la salière.png",
        "pics/les couverts les verres et la vaisselle/la saucière.png",
        "pics/les couverts les verres et la vaisselle/la soupière.png",
        "pics/les couverts les verres et la vaisselle/la tasse à expresso.png",
        "pics/les couverts les verres et la vaisselle/la tasse.png",
        "pics/les couverts les verres et la vaisselle/le bol à bouillon.png",
        "pics/les couverts les verres et la vaisselle/le bol.png",
        "pics/les couverts les verres et la vaisselle/le couteau.png",
        "pics/les couverts les verres et la vaisselle/le gobelet.png",
        "pics/les couverts les verres et la vaisselle/le plat caré.png",
        "pics/les couverts les verres et la vaisselle/le plat ovale.png",
        "pics/les couverts les verres et la vaisselle/le plat rectangulaire.png",
        "pics/les couverts les verres et la vaisselle/le plat à compartiments.png",
        "pics/les couverts les verres et la vaisselle/le poivrier.png",
        "pics/les couverts les verres et la vaisselle/le pot à lait.png",
        "pics/les couverts les verres et la vaisselle/le saladier.png",
        "pics/les couverts les verres et la vaisselle/le sucrier.png",
        "pics/les couverts les verres et la vaisselle/le verre.png"
    ]
};
